spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      properties:
        schema.registry.url: http://localhost:9095

    consumer:
      group-id: inventory
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      properties:
        schema.registry.url: http://localhost:9095
        json.value.type: com.example.order_service.dto.InventoryEvent

    topic:
      name: "order.created.v1"